Add firmware state and recovery transport contracts

diff --git a/scripts/phonebox/launch-x86_64 b/scripts/phonebox/launch-x86_64
--- a/scripts/phonebox/launch-x86_64
+++ b/scripts/phonebox/launch-x86_64
@@ -22,6 +22,7 @@ Optional environment:
   PHONEBOX_SMP        guest vCPU count, default: 4
   PHONEBOX_SSH_PORT   host TCP port forwarded to guest 22, default: 0 (disabled)
   PHONEBOX_ADB_PORT   host TCP port forwarded to guest 5555, default: 0 (disabled)
+  PHONEBOX_ADB_GUEST_PORT guest ADB port, default: 5555 (use 5556 for recovery)
   PHONEBOX_NET_MODE   user or tap, default: user
   PHONEBOX_TAP_IFNAME TAP interface name when NET_MODE=tap
   PHONEBOX_MODEM_SOCKET Unix socket for optional named modem virtio-serial port
@@ -43,6 +44,7 @@ memory=${PHONEBOX_MEMORY:-4096}
 smp=${PHONEBOX_SMP:-4}
 ssh_port=${PHONEBOX_SSH_PORT:-0}
 adb_port=${PHONEBOX_ADB_PORT:-0}
+adb_guest_port=${PHONEBOX_ADB_GUEST_PORT:-5555}
 net_mode=${PHONEBOX_NET_MODE:-user}
 tap_ifname=${PHONEBOX_TAP_IFNAME:-}
 modem_socket=${PHONEBOX_MODEM_SOCKET:-}
@@ -90,6 +92,10 @@ for value in "$ssh_port" "$adb_port"; do
         exit 2
     fi
 done
+if ! [[ $adb_guest_port =~ ^[0-9]+$ && $adb_guest_port -gt 0 && $adb_guest_port -le 65535 ]]; then
+    echo "error: PHONEBOX_ADB_GUEST_PORT must be in [1, 65535]" >&2
+    exit 2
+fi
 
 case $net_mode in
     user) ;;
@@ -123,7 +129,7 @@ if [[ $net_mode == user ]]; then
         netdev+=",hostfwd=tcp:127.0.0.1:${ssh_port}-:22"
     fi
     if [[ $adb_port != 0 ]]; then
-        netdev+=",hostfwd=tcp:127.0.0.1:${adb_port}-:5555"
+        netdev+=",hostfwd=tcp:127.0.0.1:${adb_port}-:${adb_guest_port}"
     fi
 else
     netdev="tap,id=net0,ifname=${tap_ifname},script=no,downscript=no"
